#!/usr/bin/env ruby

if(ARGV.length != 3)
  raise ArgumentError, "Provide exactly 3 arguments."
end
if(File.exist?(ARGV[2]))
  raise IOError, "Could not create output file. File \"#{ARGV[2]}\" already exists."
end

File.open(ARGV[2], "w") do |file|
  file.write(ARGV[0].to_s+","+ARGV[1].to_s)
end
